Pv2 2143 calculate save and display submission metrics at monthend
SkillsFundingAgency/das-payments-V2 pull request #1008
Opened 2020-10-26 09:28 UTC by tom-gough

2020-10-26 12:20 UTC, carlbm requested changes

2020-10-26 12:20 UTC, carlbm commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function.AcceptanceTests/SFA.DAS.Payments.Monitoring.Metrics.Function.AcceptanceTests.csproj
> +  <ItemGroup>
You could probably get rid of these

2020-10-26 16:09 UTC, ChughAkshay commented on src/SFA.DAS.Payments.Monitoring.Metrics.Data.UnitTests/MetricsPersistenceDataContextTests/GetSubmissionSummaryMetricsTests.cs
> +            Assert.True(result is null);
Updated this on PV2-2161 branch

2020-10-26 16:13 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function.AcceptanceTests/SFA.DAS.Payments.Monitoring.Metrics.Function.AcceptanceTests.csproj
> +  <ItemGroup>
we shouldn't mess around with project file

2020-10-26 16:14 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Data/MetricsPersistenceDataContext.cs
> +            var transaction = await Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
there are 2 other methods on that class that does exactly the same so lets leave it as is

2020-10-26 16:17 UTC, carlbm submitted a review, later dismissed

2020-11-04 15:40 UTC, hardik-desai-kcl approved these changes

2020-11-04 15:41 UTC, merged