Pv2 2160 inform data collections if metrics tolerance is met
SkillsFundingAgency/das-payments-V2 pull request #1012
Opened 2020-11-04 14:58 UTC by tom-gough

2020-11-04 17:01 UTC, carlbm requested changes

2020-11-05 11:45 UTC, hardik-desai-kcl requested changes

2020-11-05 11:45 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.ServiceFabric/ApplicationPackageRoot/ApplicationManifest.xml
> +    <Parameter Name="FunctionBaseUrl" DefaultValue="" />
Please rename these configs to SubmissionWindowValidationFunction* (ApiKey, BaseUrl)

2020-11-05 12:11 UTC, hardik-desai-kcl submitted a review, later dismissed

2020-11-05 16:03 UTC, hardik-desai-kcl approved these changes

2020-11-05 16:42 UTC, hardik-desai-kcl submitted a review, later dismissed

2020-11-09 11:43 UTC, carlbm submitted a review, later dismissed

2020-11-09 12:01 UTC, carlbm requested changes

2020-11-09 12:01 UTC, carlbm commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application.UnitTests/JobProcessing/PeriodEnd/PeriodEndSubmissionWindowValidationJobStatusServiceTests.cs
> +            result.Should().BeTrue();
Do we care about this? It diverts some attention from the important part of the test

2020-11-09 12:01 UTC, carlbm commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application.UnitTests/JobProcessing/PeriodEnd/PeriodEndSubmissionWindowValidationJobStatusServiceTests.cs
> +            var service = mocker.Create<PeriodEndSubmissionWindowValidationJobStatusService>();
can we call the system under test `sut`? We do in other parts of the solution

2020-11-09 12:06 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application.UnitTests/JobProcessing/PeriodEnd/PeriodEndSubmissionWindowValidationJobStatusServiceTests.cs
> +            result.Should().BeTrue();
we do care about this being true as it's reported back upstream classes

2020-11-09 12:06 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application.UnitTests/JobProcessing/PeriodEnd/PeriodEndSubmissionWindowValidationJobStatusServiceTests.cs
> +            var service = mocker.Create<PeriodEndSubmissionWindowValidationJobStatusService>();
changed

2020-11-09 12:08 UTC, carlbm approved these changes

2020-11-12 10:35 UTC, carlbm approved these changes

2020-11-12 15:47 UTC, merged