only compare Apprenticeship details from last month
SkillsFundingAgency/das-payments-V2 pull request #1023
Opened 2020-11-26 16:25 UTC by hardik-desai-kcl

2020-11-30 11:56 UTC, tom-gough requested changes

2020-11-30 11:56 UTC, tom-gough commented on src/SFA.DAS.Payments.ScheduledJobs/Monitoring/ApprenticeshipData/ApprenticeshipDataService.cs
>                  .ToListAsync();
When we do the counts (just below in this class) is it possible that there might be some cases where the time discrepancy between EmployerAndProviderApprovedOn in Commitments and CreationDate in Payments causes a false difference in count? Would there be a benefit to comparing dates without time portions? You may still get a tiny number of edge cases submitted at midnight.

2020-11-30 12:38 UTC, tom-gough submitted a review, later dismissed

2020-12-04 08:07 UTC, carlbm submitted a review, later dismissed

2020-12-07 09:39 UTC, carlbm approved these changes

2020-12-16 10:29 UTC, merged