Pv2 2242 data lock counts
SkillsFundingAgency/das-payments-V2 pull request #1026
Opened 2020-12-16 07:11 UTC by ChughAkshay

2020-12-16 11:26 UTC, hardik-desai-kcl requested changes

2020-12-16 11:26 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Data/MetricsQueryDataContext.cs
> +		            group by dle.LearnerReferenceNumber, nppf.DataLockFailureId, dle.ukprn
Please add this additional where clause to this query 

		AND dle.jobId in (select DcJobid from Payments2.LatestSuccessfulJobs Where AcademicYear = @academicYear AND CollectionPeriod = @collectionPeriod)

2020-12-16 11:26 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/SFA.DAS.Payments.Monitoring.Metrics.Domain.csproj
> +    <ProjectReference Include="..\SFA.DAS.Payments.Monitoring.Metrics.Data\SFA.DAS.Payments.Monitoring.Metrics.Data.csproj" />
this looks suspicious, could you please check if this reference is required or was it added by mistake

2020-12-16 15:45 UTC, hardik-desai-kcl approved these changes

2020-12-21 12:43 UTC, tom-gough approved these changes

2020-12-23 14:04 UTC, tom-gough approved these changes

2021-01-07 10:53 UTC, merged