Pv2 2271 duplicate records bug
SkillsFundingAgency/das-payments-V2 pull request #1034
Opened 2021-01-13 09:44 UTC by ChughAkshay

2021-01-13 11:23 UTC, carlbm requested changes

2021-01-13 11:23 UTC, carlbm commented on src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Service/LevyTransactionBatchStorageServiceTests.cs
> +            mockLevyTransactionRepository.Verify(x => x.SaveLevyTransactions(It.IsAny<List<LevyTransactionModel>>(), It.IsAny<CancellationToken>()), Times.Once);
it makes sense to check that what you are sending to the repository has data that matches what was passed in. As the method stands there is no way for this test to fail even if the method wasn't calling the repo with the correct data

2021-01-13 11:52 UTC, hardik-desai-kcl requested changes

2021-01-13 11:52 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Application/Data/Configurations/LevyTransactionModelConfiguration.cs
> +            builder.Property(x => x.TransactionType).HasColumnName(@"TransactionType").IsRequired();
IsRequired is bit misleading because underlying db column is nullable , what is your intention here?

I would just follow exiting pattern and remove IsRequired

2021-01-13 11:52 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.FundingSourceLevyTransaction.sql
> +    [FundingAccountId] BIGINT NOT NULL,
This is is the reason why the DB deployment has failed in DSI AND DST because its new column and this table already contains data from past

mark this columns as nullable

2021-01-13 11:52 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Service/LevyTransactionBatchStorageServiceTests.cs
> +
Anyway to test SaveLevyTransactionsIndividually?

2021-01-13 16:41 UTC, ChughAkshay commented on src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Service/LevyTransactionBatchStorageServiceTests.cs
> +            mockLevyTransactionRepository.Verify(x => x.SaveLevyTransactions(It.IsAny<List<LevyTransactionModel>>(), It.IsAny<CancellationToken>()), Times.Once);
change applied

2021-01-13 16:41 UTC, ChughAkshay commented on src/SFA.DAS.Payments.Application/Data/Configurations/LevyTransactionModelConfiguration.cs
> +            builder.Property(x => x.TransactionType).HasColumnName(@"TransactionType").IsRequired();
copy paste error, change applied

2021-01-13 16:41 UTC, ChughAkshay commented on src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.FundingSourceLevyTransaction.sql
> +    [FundingAccountId] BIGINT NOT NULL,
copy paste error, change applied

2021-01-13 16:49 UTC, ChughAkshay commented on src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Service/LevyTransactionBatchStorageServiceTests.cs
> +
@hardik-desai-kcl Spent a few hours on this while in dev but couldn't find a way to create an instance of "SqlException" as the class is marked sealed and the only constructor is internal. Also tried with reflection but couldn't set the "Number" property due to it being read only. Is there a way to create an instance of this class?

2021-01-14 12:40 UTC, ChughAkshay commented on src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Service/LevyTransactionBatchStorageServiceTests.cs
> +
new test now added

2021-01-14 13:12 UTC, hardik-desai-kcl submitted a review, later dismissed

2021-01-15 11:49 UTC, carlbm submitted a review, later dismissed

2021-01-18 09:12 UTC, hardik-desai-kcl submitted a review, later dismissed

2021-01-18 10:51 UTC, hardik-desai-kcl submitted a review, later dismissed

2021-01-28 14:24 UTC, hardik-desai-kcl approved these changes

2021-02-01 16:06 UTC, tom-gough submitted a review, later dismissed

2021-02-02 10:33 UTC, tom-gough requested changes

2021-02-02 10:33 UTC, tom-gough commented on src/SFA.DAS.Payments.Model.Core/Entities/LevyTransactionModel.cs
>      }
new fields added that are nullable in DB should be nullable on here

2021-02-04 10:25 UTC, tom-gough approved these changes

2021-02-04 11:13 UTC, merged