Pv2 2268 redundancy bil funding source bug
SkillsFundingAgency/das-payments-V2 pull request #1035
Opened 2021-01-13 09:48 UTC by tom-gough

2021-01-13 11:36 UTC, hardik-desai-kcl requested changes

2021-01-13 11:36 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.Application/Mapping/EarningEventBuilderBase.cs
> +                    var startPeriod = currentPriceEpisode.PriceEpisodeValues.PriceEpisodeRedStartDate.Value.GetPeriodFromDate();
I would rename startPeriod to redundancystartPeriod and nextPeriod to redundancyStoppedPeriod or redundancyEndPeriod or redundancyFinishedPeriod ?

2021-01-13 11:36 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +            splitResults.Add(redundancyEarningEvent);
even though the end result is the same I would move this line at the bottom to make it clear that 
split results contains updated redundancy earnings, here its bit lost in other code and someone might not see it

2021-01-13 11:36 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +        public List<ApprenticeshipContractTypeEarningsEvent> SplitContractEarningByRedundancyDate(ApprenticeshipContractTypeEarningsEvent earningEvent,
I would rename the method to reflect the new behaviour, 1 its not doing the split by date and 2 its not doing split at all  in one instance (reinstating that if statement would mean method will always be doing split)

2021-01-13 11:36 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +        public List<FunctionalSkillEarningsEvent> SplitFunctionSkillEarningByRedundancyDate(FunctionalSkillEarningsEvent functionalSkillEarning, List<byte> redundancyPeriods)
same as SplitContractEarningByRedundancyDate

2021-01-13 11:36 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +            splitResults.Add(redundancyEarningEvent);
same as SplitContractEarningByRedundancyDate

2021-01-14 08:19 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/PV2_2268_Steps.cs
> +            //covered by FM36s imported in first step
done

2021-01-14 08:19 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/PV2_2268_Steps.cs
> +        private void ScriptInApprenticeshipData()
done

2021-01-14 08:19 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application/Mapping/EarningEventBuilderBase.cs
> +                    var startPeriod = currentPriceEpisode.PriceEpisodeValues.PriceEpisodeRedStartDate.Value.GetPeriodFromDate();
done

2021-01-14 08:22 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +            splitResults.Add(redundancyEarningEvent);
That doesn't really match the approach we have gone for with the ApprenticeshipContractTypeEarningsEvent. The idea is we add both earning events (if required) to the list at the top, then set them up correctly in the rest of the method. If we were to move this to the bottom we would be adding the earning event at the top, but then the redundancy earning event at the bottom. If we were to move both to the bottom we would have to change the clean "return early" code on lines 23-25

2021-01-14 08:22 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +        public List<ApprenticeshipContractTypeEarningsEvent> SplitContractEarningByRedundancyDate(ApprenticeshipContractTypeEarningsEvent earningEvent,
done

2021-01-14 08:22 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +        public List<FunctionalSkillEarningsEvent> SplitFunctionSkillEarningByRedundancyDate(FunctionalSkillEarningsEvent functionalSkillEarning, List<byte> redundancyPeriods)
done

2021-01-14 08:22 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application/Services/RedundancyEarningService.cs
> +            splitResults.Add(redundancyEarningEvent);
done

2021-01-14 09:57 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/ApprenticeshipContractTypeEarningsEventBuilderTest.cs
> +                .Should().HaveCount(1);
sensible ye, done

2021-01-14 10:08 UTC, hardik-desai-kcl approved these changes

2021-01-21 13:27 UTC, merged