Pv2 2308 store period end completion date
SkillsFundingAgency/das-payments-V2 pull request #1039
Opened 2021-02-26 10:24 UTC by tom-gough

2021-02-26 11:57 UTC, carlbm submitted a review, later dismissed
Approving, but I'm not sure why the unit test strategy has changed

2021-03-08 15:45 UTC, carlbm requested changes

2021-03-08 15:45 UTC, carlbm commented on src/SFA.DAS.Payments.Application/Infrastructure/Logging/PaymentsLoggerConfigurationBuilder.cs
> +                .Filter.ByExcluding(evnt => evnt.Exception != null && string.Equals(evnt.Exception.ToString(), "license", StringComparison.OrdinalIgnoreCase));
This is a change to behaviour and should be removed (contains vs equals)

2021-03-08 21:45 UTC, ChughAkshay commented on src/SFA.DAS.Payments.Model.Core/Entities/CollectionPeriodModel.cs
> +        public DateTime CompletionDate { get; set; }
Minor observation:
I'm probably wrong but shouldn't all the ValueType properties other than Id be nullable (in this class only) to prevent the following condition:
- If any of the properties on PeriodEndStoppedEvent are made nullable in a future release the app would be saving nulls as 0's to the table.

2021-03-09 09:44 UTC, tom-gough commented on src/SFA.DAS.Payments.ProviderPayments.Application/Services/CollectionPeriodStorageService.cs
> +                                    && x.EndTime.Value != null)
No, this is what was causing the issue Pawan found. It seems to be a nuance with the DateTimeOffset object.

2021-03-09 09:45 UTC, tom-gough commented on src/SFA.DAS.Payments.ProviderPayments.Application/Services/CollectionPeriodStorageService.cs
> +        private DateTime? GetReferenceDataValidationDate(short academicYear, byte period)
Fixed

2021-03-09 10:06 UTC, carlbm approved these changes

2021-03-17 10:04 UTC, merged