Pv2 2393 maintain record of ukprns that need reprocessing
SkillsFundingAgency/das-payments-V2 pull request #1040
Opened 2021-03-12 10:17 UTC by carlbm

2021-03-12 15:10 UTC, hardik-desai-kcl requested changes

2021-03-12 15:10 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/SubmissionSucceededHandler.cs
> +            await repository.RemoveUkrpnFromReprocessingList(message.Ukprn);
this method should be wrapped in the service class because you have a service to add the record so why go direct to remove?

2021-03-12 15:10 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/ProviderRequiringReprocessingService.cs
> +        Task AddUkprnIfNotExists(long ukprn);
remove method is missing

2021-03-12 15:10 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/ProviderRequiringReprocessingService.cs
> +            logger.LogInfo($"Finished adding Ukprn to ProviderRequiringReprocessing table for Ukprn: {ukprn}");
not requesting a any change but this might be bit misleading when the provider already exists, I would just flip the logic and log the fact that provider already exists in the DB

2021-03-12 15:10 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Data/PeriodEndDataContext.cs
> +        public PeriodEndDataContext(DbContextOptions<PeriodEndDataContext> options) : base(options)
remove extra spaces and I don't this this constructor is in use so remove that as well

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Infrastructure/FeatureScopedBootstrapper.cs
> +                    return new PeriodEndDataContext(configHelper.PaymentsConnectionString);
Do we not use the TestPaymentsDataContext usually in e2e tests?

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ProvidersRequiringResubmissionSteps.cs
> +            await WaitForIt(() =>
Should this be WaitForItUnexpected?

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.ProviderRequiringReprocessing.sql
> +	Ukprn BIGINT NULL,
When will we ever want to add a record in this table with a null ukprn?

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/ApprenticeshipUpdatedHandler.cs
> +            logger.LogDebug($"Apprenticeship Updated. Adding Ukprn: {message.Ukprn} to list for reprocessing");
should the log entry say that it won't be added if it already exists?

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +            //dataContext.ProvidersRequiringReprocessing.FromSql($"DELETE [Payments2].[ProviderRequiringReprocessing] WHERE Ukprn = {ukprn}");
use it or lose it

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +        public async Task<ProviderRequiringReprocessingEntity> RecordForProviderThatRequiresReprocessing(long ukprn)
nit picking here but I don't like this method name because it looks like "Record" is a verb and it's writing to the db

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/ProviderRequiringReprocessingService.cs
> +            logger.LogDebug($"Adding Ukprn to ProviderRequiringReprocessing table for Ukprn: {ukprn}");
add "if not exists" to this to make the logs clearer?

2021-03-12 16:19 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Data/PeriodEndDataContext.cs
> +        public async Task<int> SaveChanges(CancellationToken cancellationToken = default(CancellationToken))
Not sure what the purpose of this is vs just using SaveChangesAsync from the calling code?

2021-03-15 08:00 UTC, carlbm commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ProvidersRequiringResubmissionSteps.cs
> +        public void GivenThereIsNoPreviousSubmissionFromProviderInCurrentCollectionPeriod()
Improved the language. There are still 3 statements though, as they are stating different things

2021-03-15 08:00 UTC, carlbm commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ProvidersRequiringResubmissionSteps.cs
> +        public async Task ThenNewRecordWillBeAddedToTheProviderRequiringReprocessingTable()
see above

2021-03-15 08:00 UTC, carlbm commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ProvidersRequiringResubmissionSteps.cs
> +        [When(@"there is a change at approvals side")]
addressed

2021-03-15 08:03 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +    public interface IPeriodEndRepository
Changed

2021-03-15 08:05 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +        Task<ProviderRequiringReprocessingEntity> RecordForProviderThatRequiresReprocessing(long ukprn);
Changed

2021-03-15 08:06 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +            //dataContext.ProvidersRequiringReprocessing.FromSql($"DELETE [Payments2].[ProviderRequiringReprocessing] WHERE Ukprn = {ukprn}");
Gone

2021-03-15 08:12 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/ProviderRequiringReprocessingService.cs
> +            logger.LogInfo($"Finished adding Ukprn to ProviderRequiringReprocessing table for Ukprn: {ukprn}");
Added logging for case where the record exists

2021-03-15 08:45 UTC, carlbm commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Infrastructure/FeatureScopedBootstrapper.cs
> +                    return new PeriodEndDataContext(configHelper.PaymentsConnectionString);
I thought we used that for test data, but continue to use the production data contexts where there were methods available? See: `PeriodEndSteps`

2021-03-15 08:51 UTC, carlbm commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ProvidersRequiringResubmissionSteps.cs
> +            await WaitForIt(() =>
I don't think so. We are waiting for the record to be deleted (ie expecting a change of state), where the `WaitForUnexpected` method seems to require the passing condition to remain otherwise fail (so no change of state).

2021-03-15 08:52 UTC, carlbm commented on src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.ProviderRequiringReprocessing.sql
> +	Ukprn BIGINT NULL,
Good spot... updated

2021-03-15 08:53 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/ApprenticeshipUpdatedHandler.cs
> +            logger.LogDebug($"Apprenticeship Updated. Adding Ukprn: {message.Ukprn} to list for reprocessing");
Updated

2021-03-15 08:54 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +            //dataContext.ProvidersRequiringReprocessing.FromSql($"DELETE [Payments2].[ProviderRequiringReprocessing] WHERE Ukprn = {ukprn}");
👍

2021-03-15 08:54 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +        public async Task<ProviderRequiringReprocessingEntity> RecordForProviderThatRequiresReprocessing(long ukprn)
Updated

2021-03-15 08:54 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/ProviderRequiringReprocessingService.cs
> +            logger.LogDebug($"Adding Ukprn to ProviderRequiringReprocessing table for Ukprn: {ukprn}");
Updated

2021-03-15 08:58 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Data/PeriodEndDataContext.cs
> +        public async Task<int> SaveChanges(CancellationToken cancellationToken = default(CancellationToken))
No purpose... updated now

2021-03-15 10:17 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ProvidersRequiringResubmissionSteps.cs
> +            await WaitForIt(() =>
Understood

2021-03-15 10:18 UTC, tom-gough approved these changes

2021-03-15 10:32 UTC, hardik-desai-kcl requested changes

2021-03-15 10:32 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/ProvidersRequiringReprocessingRepository.cs
> +        public async Task<ProviderRequiringReprocessingEntity> GetExisting(long ukprn)
this is not in use and can be removed

2021-03-15 11:11 UTC, hardik-desai-kcl approved these changes

2021-03-19 09:01 UTC, carlbm commented
PV2-2394 is build on top of this branch. Will use the PR for that branch now that both have been approved

2021-03-19 09:01 UTC, closed without merging