Pv2 2394 providers requiring resubmission function
SkillsFundingAgency/das-payments-V2 pull request #1041
Opened 2021-03-15 15:41 UTC by carlbm

2021-03-16 15:04 UTC, tom-gough submitted a review, later dismissed

2021-03-16 15:04 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/SubmissionJobsService.cs
> +            providers.RemoveAll(x => providersToExclude.Contains(x.Ukprn));
nit picking slightly again but would a .Where be more readable here?

providers.Where(x => providersToExclude.Any(y => y == x.Ukprn))

Just personal preference really but wondered what you think?

2021-03-17 08:16 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Repositories/PeriodEndRepository.cs
> +            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
Added logging

2021-03-17 08:44 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/SubmissionJobsService.cs
> +            providers.RemoveAll(x => providersToExclude.Contains(x.Ukprn));
I thought that as we're removing the items in the list it made more sense to use the `Remove` variant over the `Where`.

2021-03-17 11:38 UTC, hardik-desai-kcl requested changes

2021-03-17 11:38 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Function/Infrastructure/IoC/Modules/FunctionsModule.cs
> +                    return new PeriodEndDataContext(dbContextOptions);
in the other branch where we handle the apprenticeship updated events and submission successful events you have used the constructor with connection string and here you have used dbContextOptions constructor and reason why two different way of doing this?

2021-03-17 11:38 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Function/Infrastructure/Configuration/SubmissionMetricsConfiguration.cs
> +    public class SubmissionMetricsConfiguration : ISubmissionMetricsConfiguration
ProvidersRequiringReprocessingConfiguration

2021-03-17 11:38 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/SubmissionJobsService.cs
> +    public class SubmissionJobsService : ISubmissionJobsService
ProvidersRequiringReprocessingService

2021-03-17 11:38 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.AcceptanceTests/App.config
> +    <add key="FunctionUri" value="" />
unless this is how we have done in the other projects could you please give this variable a good name?

2021-03-17 11:43 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.AcceptanceTests/App.config
> +    <add key="FunctionUri" value="" />
✔️

2021-03-17 11:47 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Application/Services/SubmissionJobsService.cs
> +    public class SubmissionJobsService : ISubmissionJobsService
✔️

2021-03-17 11:50 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Function/Infrastructure/Configuration/SubmissionMetricsConfiguration.cs
> +    public class SubmissionMetricsConfiguration : ISubmissionMetricsConfiguration
✔️

2021-03-17 11:52 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Function/Infrastructure/IoC/Modules/FunctionsModule.cs
> +                    return new PeriodEndDataContext(dbContextOptions);
We copied the existing pattern in both cases

2021-03-17 12:01 UTC, carlbm commented on src/SFA.DAS.Payments.PeriodEnd.Function/Infrastructure/IoC/Modules/FunctionsModule.cs
> +                    return new PeriodEndDataContext(dbContextOptions);
Using the connection string constructor now

2021-03-17 12:04 UTC, hardik-desai-kcl approved these changes

2021-03-18 14:39 UTC, hardik-desai-kcl submitted a review, later dismissed

2021-04-01 13:17 UTC, hardik-desai-kcl approved these changes

2021-04-01 13:22 UTC, merged