Pv2 2469 inform tolerance dc
SkillsFundingAgency/das-payments-V2 pull request #1051
Opened 2021-05-12 10:17 UTC by tom-gough

2021-05-12 10:59 UTC, hardik-desai-kcl requested changes

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
> +            if (taskType == PeriodEndTaskType.PeriodEndStart ||
This can be simplified by using inverse of the current list i.e. periodendstop and filesubmission job

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
>                      logger.LogDebug("Returning as this is either a PeriodEndStop or PeriodEndRequestReports event");
update this log to remove PeriodEndRequestReports

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.JobContextMessageHandling/JobStatus/JobStatusService.cs
> +        Task<bool> WaitForDcJobToFinish(long dcJobId, CancellationToken cancellationToken);
rename this to WaitForPeriodEndJobToFinish

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function/ValidatePeriodEndReportHttpTrigger.cs
> +    public static class ValidatePeriodEndReportHttpTrigger
rename this to match the client or rename the client to match this name 
my preference would be PeriodEndRequestReportHttpTrigger

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function/ValidatePeriodEndReportHttpTrigger.cs
> +        [FunctionName("ValidatePeriodEndReport")]
same as above my preference would be PeriodEndRequestReport

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function/Infrastructure/IoC/Modules/FunctionsModule.cs
> +            builder.RegisterType<PeriodEndMetricsService>().AsImplementedInterfaces().InstancePerLifetimeScope();
make sure to delete these registration from the Monitoring.Metrics infrastruction as its not in use over there anymore

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Infrastructure/Ioc/JobServiceModule.cs
> +                    return new PeriodEndReportValidationClient(configHelper.GetSetting("PeriodEndReportValidationFunctionApiKey"), configHelper.GetSetting("SubmissionWindowValidationFunctionBaseUrl")
I would ask DevOps to rename this variable as its now used in two different places
SubmissionWindowValidationFunctionBaseUrl to MonitoringMetricsFunctionsBaseUrl

2021-05-12 10:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/PeriodEndReportValidationClient.cs
> +    public class PeriodEndReportValidationClient : IPeriodEndReportValidationClient
same as the function 
but my preference would be PeriodEndRequestReportClient
PeriodEndRequestReport is not the best name but thats what we are getting from DC so we might as well keep using that name everywhere

2021-05-12 11:04 UTC, hardik-desai-kcl requested changes

2021-05-12 11:04 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
>                  case PeriodEndTaskType.PeriodEndStart:
not sure but you might have to add a new JobType for job service to save that job to DB 
have a look at 

public enum JobType

2021-05-12 11:08 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Infrastructure/Ioc/JobServiceModule.cs
> +                    return new PeriodEndReportValidationClient(configHelper.GetSetting("PeriodEndReportValidationFunctionApiKey"), configHelper.GetSetting("SubmissionWindowValidationFunctionBaseUrl")
Agreed "MetricsFunctionBaseUrl" with Toby

2021-05-12 11:08 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Infrastructure/Ioc/JobServiceModule.cs
> +                    return new PeriodEndReportValidationClient(configHelper.GetSetting("PeriodEndReportValidationFunctionApiKey"), configHelper.GetSetting("SubmissionWindowValidationFunctionBaseUrl")
Same thing can be done for api key, agreed "MetricsFunctionApiKey"

2021-05-13 08:38 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
> +            if (taskType == PeriodEndTaskType.PeriodEndStart ||
I think it needs to be a switch such that different event types can be returned for each PeriodEndTaskType

2021-05-13 08:38 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
>                      logger.LogDebug("Returning as this is either a PeriodEndStop or PeriodEndRequestReports event");
done

2021-05-13 08:38 UTC, tom-gough commented on src/SFA.DAS.Payments.JobContextMessageHandling/JobStatus/JobStatusService.cs
> +        Task<bool> WaitForDcJobToFinish(long dcJobId, CancellationToken cancellationToken);
done

2021-05-13 08:38 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function/ValidatePeriodEndReportHttpTrigger.cs
> +    public static class ValidatePeriodEndReportHttpTrigger
done

2021-05-13 08:38 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function/ValidatePeriodEndReportHttpTrigger.cs
> +        [FunctionName("ValidatePeriodEndReport")]
done

2021-05-13 08:39 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Metrics.Function/Infrastructure/IoC/Modules/FunctionsModule.cs
> +            builder.RegisterType<PeriodEndMetricsService>().AsImplementedInterfaces().InstancePerLifetimeScope();
done, MetricsModule wasn't even referenced anymore so it's gone

2021-05-13 08:39 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/PeriodEndReportValidationClient.cs
> +    public class PeriodEndReportValidationClient : IPeriodEndReportValidationClient
done

2021-05-13 13:54 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
>                  case PeriodEndTaskType.PeriodEndStart:
fixed

2021-05-19 10:02 UTC, hardik-desai-kcl approved these changes

2021-05-26 10:28 UTC, merged