Pv2 2275 duplicate provider clawbacks
SkillsFundingAgency/das-payments-V2 pull request #1053
Opened 2021-06-09 09:28 UTC by hardik-desai-kcl

2021-06-10 07:26 UTC, tom-gough requested changes

2021-06-10 07:26 UTC, tom-gough commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/ClawbackRemovedLearnerAimsProcessor.cs
> +                .SelectMany(paymentId => paymentId);
Consider changing this to an expression tree?

2021-06-10 07:26 UTC, tom-gough commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/ClawbackRemovedLearnerAimsProcessor.cs
> +            //NOTE: DO NOTE CHANGE THE ORDER OF ASSIGNMENT BELLOW
Is it worth splitting this down to be:

```
            clawbackPayment.Id = 0;
            clawbackPayment.Amount *= -1;
            clawbackPayment.JobId = message.JobId;
            clawbackPayment.CollectionPeriod = message.CollectionPeriod.Clone();
            clawbackPayment.IlrSubmissionDateTime = message.IlrSubmissionDateTime;

            //NOTE: DO NOTE CHANGE THE ORDER OF ASSIGNMENT BELOW
            clawbackPayment.ClawbackSourcePaymentEventId = clawbackPayment.EventId;
            clawbackPayment.EventId = Guid.NewGuid();

            clawbackPayment.EventTime = DateTimeOffset.UtcNow;

            clawbackPayment.RequiredPaymentEventId = null;
            clawbackPayment.EarningEventId = Guid.Empty;
            clawbackPayment.FundingSourceEventId = Guid.Empty;
```
            
So it's super obvious why that comment is there

2021-06-10 07:26 UTC, tom-gough commented on src/SFA.DAS.Payments.RequiredPayments.Application/Mapping/RequiredPaymentsProfile.cs
> +                //These 4 Fields are not available in PaymentModel and therefore will not be written to DB so no need to map them, also SequenceNumber
Should sequence number be explicitly ignored too?

2021-06-10 07:26 UTC, tom-gough commented on src/SFA.DAS.Payments.RequiredPayments.Application/Mapping/RequiredPaymentsProfile.cs
> +                    //SequenceNumber = s.SequenceNumber
Use it or lose it, see above comment

2021-06-10 07:26 UTC, tom-gough commented on src/SFA.DAS.Payments.RequiredPayments.Application/Repositories/PaymentClawbackRepository.cs
> +        public async Task<List<PaymentModel>> GetLearnerPaymentHistory(
GetUntrackedLearnerPaymentHistory? So it's clear to the calling code the entities are no tracked and adds an extra level of "I should not remove .AsNoTracking()" in the next developer's head

2021-06-10 08:48 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.RequiredPayments.Application/Mapping/RequiredPaymentsProfile.cs
> +                //These 4 Fields are not available in PaymentModel and therefore will not be written to DB so no need to map them, also SequenceNumber
you cant explicitly ignore the sequence number because its mapped using new construct

2021-06-10 08:49 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/ClawbackRemovedLearnerAimsProcessor.cs
> +            //NOTE: DO NOTE CHANGE THE ORDER OF ASSIGNMENT BELLOW
done

2021-06-10 08:50 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.RequiredPayments.Application/Mapping/RequiredPaymentsProfile.cs
> +                    //SequenceNumber = s.SequenceNumber
done

2021-06-10 08:55 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/ClawbackRemovedLearnerAimsProcessor.cs
> +                .SelectMany(paymentId => paymentId);
done

2021-06-10 08:59 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.RequiredPayments.Application/Repositories/PaymentClawbackRepository.cs
> +        public async Task<List<PaymentModel>> GetLearnerPaymentHistory(
I dont think "Untracked" appropriate as its mostly framework behavious, we want method name to describe function behaviour

2021-06-10 09:48 UTC, tom-gough commented on src/SFA.DAS.Payments.RequiredPayments.Application/Mapping/RequiredPaymentsProfile.cs
> +                //These 3 Fields are not available in PaymentModel and therefore will not be written to DB so no need to map them, also SequenceNumber
Why is sequence number handled differently?

2021-06-10 09:51 UTC, tom-gough approved these changes

2021-06-11 10:56 UTC, tom-gough submitted a review, later dismissed

2021-06-16 10:02 UTC, tom-gough approved these changes
Approved Hardik's latest production code changes

2021-06-16 10:36 UTC, tom-gough approved these changes
Approved update to payments insertion

2021-06-16 12:57 UTC, tom-gough approved these changes

2021-06-16 13:44 UTC, ChughAkshay approved these changes

2021-06-23 10:36 UTC, merged