Pv2 2616 fm36 nuget update
SkillsFundingAgency/das-payments-V2 pull request #1057
Opened 2021-07-09 10:23 UTC by tom-gough

2021-07-16 13:48 UTC, hardik-desai-kcl requested changes

2021-07-16 13:48 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
> +                //newPriceEpisode.PriceEpisodeValues.PriceEpisodeSFAContribPct = sfaContributionPercent; TODO 2616 Acceptance Tests
I am guessing this is no longer required and can be removed

2021-07-16 13:48 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.AcceptanceTests/Steps/EarningEventsStepsBase.cs
> +                        //PriceEpisodeESFAContribPct = SfaContributionPercentage, TODO 2616 Acceptance Tests
remove if done

2021-07-16 13:48 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PerformanceTests/TestsBase.cs
> +                    //PriceEpisodeSFAContribPct = .9M, TODO 2616 Acceptance Tests
do we need to fix this?

2021-07-16 13:48 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.EarningEvents.Application/Mapping/SfaContributionPercentageExtensions.cs
> +                .SingleOrDefault(x => x.AttributeName == "PriceEpisodeSFAContribPct");
are we ever going to get values from PriceEpisodeSFAContribPct Attribute?

2021-07-16 13:53 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
> +                //newPriceEpisode.PriceEpisodeValues.PriceEpisodeSFAContribPct = sfaContributionPercent; TODO 2616 Acceptance Tests
done

2021-07-16 13:53 UTC, tom-gough commented on src/SFA.DAS.Payments.PerformanceTests/TestsBase.cs
> +                    //PriceEpisodeSFAContribPct = .9M, TODO 2616 Acceptance Tests
done

2021-07-16 13:53 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.AcceptanceTests/Steps/EarningEventsStepsBase.cs
> +                        //PriceEpisodeESFAContribPct = SfaContributionPercentage, TODO 2616 Acceptance Tests
done

2021-07-16 13:55 UTC, tom-gough commented on src/SFA.DAS.Payments.EarningEvents.Application/Mapping/SfaContributionPercentageExtensions.cs
> +                .SingleOrDefault(x => x.AttributeName == "PriceEpisodeSFAContribPct");
Yes for 2021 FM36s only, in theory the 2021 schema contains both, and the code will only check for PriceEpisodeSFAContribPct if it can't find PriceEpisodeESFAContribPct. I left it in for belt and braces but can remove if you would prefer.

2021-07-16 14:24 UTC, hardik-desai-kcl submitted a review, later dismissed

2021-07-19 09:12 UTC, hardik-desai-kcl submitted a review, later dismissed
I did last two changes, but Tom have code reviewed them and given verbal approve and because Tom raised original PR, he can't approve it so I am approving it

2021-07-20 15:11 UTC, tom-gough commented
Approved Hardik's latest commits

2021-08-02 13:25 UTC, merged