PV2-252-reenable-acceptance-test
SkillsFundingAgency/das-payments-V2 pull request #1071
Opened 2021-09-24 08:56 UTC by hardik-desai-kcl

…cted

2021-09-24 09:01 UTC, AkshayBanifatsyevichChugh submitted a review, later dismissed

2021-09-27 09:18 UTC, tom-gough requested changes

2021-09-27 09:18 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Inconsistent Submission Data/PV2-288 Levy learner, start date moved forward, no payments refunded.feature
> +		I want a learner that moves start date forward on prog payments and English & Maths refunded, to be paid correct amount,
not super clear what this is trying to say, perhaps "I want a learner that moves start date forward, with on prog and English & Maths payments that have been refunded, to be paid correct amount"

2021-09-27 09:18 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Learner Change of Circumstances/PV2-290 - Levy learner changes standard with change to price.feature
> +		| Aim Type         | Aim Reference | Start Date                   | Planned Duration | Actual Duration | Aim Sequence Number | Programme Type | Standard Code | Funding Line Type             | Compl
what is aim type? I can kind of guess that it's something added to represent standards vs frameworks, but we don't represent it this way anywhere else and generally I thought it was referred to as standard or framework, not programme, and a programme type is just something you need as part of a standard?

2021-09-27 09:18 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Learner Change of Circumstances/PV2-296 - Levy learner goes on a planned break.feature
> + #Scenario: Apprentice goes on a planned break midway through the learning episode and this is notified through the ILR
I get that this is existing commented out code, but do we definitely still want it?

2021-09-27 12:15 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Learner Change of Circumstances/PV2-290 - Levy learner changes standard with change to price.feature
> +		| Aim Type         | Aim Reference | Start Date                   | Planned Duration | Actual Duration | Aim Sequence Number | Programme Type | Standard Code | Funding Line Type             | Compl
| Aim Type             |
| Maths or English |
| Programme         |

2021-09-27 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Inconsistent Submission Data/PV2-288 Levy learner, start date moved forward, no payments refunded.feature
> +		I want a learner that moves start date forward on prog payments and English & Maths refunded, to be paid correct amount,
fixed

2021-09-27 12:25 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Learner Change of Circumstances/PV2-296 - Levy learner goes on a planned break.feature
> + #Scenario: Apprentice goes on a planned break midway through the learning episode and this is notified through the ILR
this is the old style acceptance tests

2021-09-27 14:13 UTC, tom-gough submitted a review, later dismissed
Checking tests on my machine, all changed tests passing

2021-09-28 10:33 UTC, AkshayBanifatsyevichChugh approved these changes

2021-09-29 09:35 UTC, merged