PV2-2748-additional-loggin-in-monitorning-service
SkillsFundingAgency/das-payments-V2 pull request #1081
Opened 2021-11-01 09:59 UTC by hardik-desai-kcl

2021-11-01 13:14 UTC, AkshayBanifatsyevichChugh approved these changes

2021-11-01 13:14 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/PeriodEndStartJobStatusService.cs
> +                properties.Add("jobsWithoutSubmissionSummaries", string.Join(", ", jobsWithoutSubmissionSummariesPresent.Select(j => j.ToJson())));
I think these property names should also be capitalised

2021-11-03 12:28 UTC, AkshayBanifatsyevichChugh requested changes

2021-11-03 12:28 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Jobs.Data/JobsDataContext.cs
> +        Task<List<OutstandingJobResult>> GetOutstandingOrTimedOutJobs(JobModel startTime, CancellationToken cancellationToken);
Type is JobModel but variable is still named startTime

2021-11-03 13:34 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Jobs.Data/JobsDataContext.cs
> +        Task<List<OutstandingJobResult>> GetOutstandingOrTimedOutJobs(JobModel startTime, CancellationToken cancellationToken);
fixed it

2021-11-03 13:36 UTC, tom-gough approved these changes

2021-11-03 13:42 UTC, AkshayBanifatsyevichChugh approved these changes

2021-11-04 16:44 UTC, AkshayBanifatsyevichChugh approved these changes

2021-11-09 09:43 UTC, merged