Pv2 2809 net negative payments metrics
SkillsFundingAgency/das-payments-V2 pull request #1097
Opened 2022-01-31 13:40 UTC by AkshayBanifatsyevichChugh

2022-02-03 13:58 UTC, hardik-desai-kcl requested changes

2022-02-03 13:58 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
> +                var learnerPayments = providerLearnerPayments?.Where(x => x.LearnerUln == uln && x.Total > 0m).ToList();
check if  Total != 0m

2022-02-03 13:58 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
> +                var learnerDataLocks = providerLearnerDataLockedEarnings?.Where(x => x.LearnerUln == uln).ToList();
check if  Total != 0m

2022-02-03 13:58 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
>          }
This method can be simplified as bellow if the duplicates is not an issue

            negativeEarnings = new NegativeEarningsContractTypeAmounts();

            if (providerLearnerNegativeDcEarnings == null || providerLearnerNegativeDcEarnings.Count == 0) return;

            foreach (var learner in providerLearnerNegativeDcEarnings)
            {
                //if learner has payments, then do not add negative earnings to provider summary
                var learnerPayments = providerLearnerPayments?.Where(x => x.LearnerUln == learner.Uln && x.Total > 0m).ToList();
                if (learnerPayments != null && learnerPayments.Count != 0) continue;

                //if learner has data locks, then do not add negative earnings to provider summary
                var learnerDataLocks = providerLearnerDataLockedEarnings?.Where(x => x.LearnerUln == learner.Uln).ToList();
                if (learnerDataLocks != null && learnerDataLocks.Count != 0) continue;

                switch (learner.ContractType)
                {
                    case ContractType.Act1:
                        negativeEarnings.ContractType1 =+ learner.NegativeEarningsTotal;
                        break;

                    case ContractType.Act2:
                        negativeEarnings.ContractType2 =+ learner.NegativeEarningsTotal;
                        break;
                }
            }

2022-02-03 13:58 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
> +            var distinctLearnerUlns = providerLearnerNegativeDcEarnings.Select(x => x.Uln).Distinct().ToList();
are you sure there are duplicates? if there ware duplicate's why there are duplicates?

2022-02-03 16:30 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application/Infrastructure/Ioc/MetricsModule.cs
>  using SFA.DAS.Payments.Monitoring.Metrics.Application.Submission;
removed

2022-02-03 16:30 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Model/ProviderLearnerDataLockEarningsTotal.cs
> +    public class ProviderLearnerDataLockEarningsTotal
change applied

2022-02-03 16:35 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Model/ProviderLearnerContractTypeAmounts.cs
> +    public class ProviderLearnerContractTypeAmounts : ProviderContractTypeAmounts
change applied

2022-02-03 16:35 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Model/ProviderLearnerNegativeEarningsTotal.cs
> +    public class ProviderLearnerNegativeEarningsTotal
change applied

2022-02-03 16:35 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application/PeriodEnd/PeriodEndMetricsRepository.cs
> +        Task<List<ProviderLearnerContractTypeAmounts>> GetPaymentAmountsForLearnersByContractType(List<long> learnerUlns, short academicYear, CancellationToken cancellationToken);
change applied

2022-02-03 16:36 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application/PeriodEnd/PeriodEndMetricsRepository.cs
> +        Task<List<ProviderLearnerDataLockEarningsTotal>> GetDataLockedAmountsForLearners(List<long> learnerUlns, short academicYear, byte collectionPeriod, CancellationToken cancellationToken);
change applied

2022-02-04 09:33 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
> +                var learnerPayments = providerLearnerPayments?.Where(x => x.LearnerUln == uln && x.Total > 0m).ToList();
change applied

2022-02-04 09:33 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
> +                var learnerDataLocks = providerLearnerDataLockedEarnings?.Where(x => x.LearnerUln == uln).ToList();
change applied

2022-02-04 15:12 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.Monitoring.Metrics.Domain/PeriodEnd/PeriodEndProviderSummary.cs
>          }
change applied

2022-02-07 14:30 UTC, hardik-desai-kcl submitted a review, later dismissed

2022-03-01 11:33 UTC, hardik-desai-kcl submitted a review, later dismissed

2022-03-10 13:43 UTC, hardik-desai-kcl approved these changes

2022-03-10 15:24 UTC, merged