Mandrici/monitoringalerts ei2004
SkillsFundingAgency/das-payments-V2 pull request #1151
Opened 2023-01-24 12:03 UTC by mandrici

Adds SFA.DAS.Payments.Monitoring.Alerts.Function project with the two functions required to post to the two separate Slack Channels. Refactoring of existing function code and unit tests added
Switches to System.Text.Json from Newtonsoft. Adds custom converter from json into dynamic.
Adds SFA.DAS.Payments.Monitoring.Metrics.CustomEventsDataHelper function to facilitate seeding custom events data into application insights.

2023-01-24 12:58 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function/SendSlackAlert.cs
> +        private async Task PostSlackAlert(HttpRequest req, ILogger log, string slackChannelUri)
Would be good to move this functionality out of the Azure function and into a dependency service

2023-01-24 12:59 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function/SendSlackAlert.cs
> +            var apiInsightsClient = _factory.CreateClient("pollyClient");
This is the same client as used for Slack, is that correct?

2023-01-24 13:01 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Metrics.CustomEventsDataHelper/Functions/GeneratePeriodEndEvent.cs
> +        private static string GenerateAccuracyEvent(string eventName, HttpRequest req, ILogger log, ITelemetry telemetry)
Another candidate for splitting out into a separate service

2023-01-24 13:04 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function/SendSlackAlert.cs
> +            var apiInsightsClient = _factory.CreateClient("pollyClient");
Same retry policy configuration - but then they're configured differently in terms of base address.

2023-01-24 13:06 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function/SendSlackAlert.cs
> +        private async Task PostSlackAlert(HttpRequest req, ILogger log, string slackChannelUri)
Ok, I understand where you're coming from. I'll check this with Tony -> the existing code was one long function uploaded manually to Azure. Will update here when I've a steer about this.

2023-01-24 13:09 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Metrics.CustomEventsDataHelper/Functions/GeneratePeriodEndEvent.cs
> +        private static string GenerateAccuracyEvent(string eventName, HttpRequest req, ILogger log, ITelemetry telemetry)
May be overblown for this helper but I'll check with Tony on this too.

2023-01-24 13:18 UTC, Stephek requested changes
Generally needs refactoring following SOLID principles.

2023-01-24 14:11 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function/SendSlackAlert.cs
> +using Newtonsoft.Json;
done

2023-01-31 10:45 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/Helpers/SlackAlertHelperTests.cs
> +        [Test]
Using the TestCase attribute would reduce the number of tests required

2023-01-31 10:46 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/Helpers/SlackAlertHelperTests.cs
> +        #region GetEmojiTests
Rather than using regions, better to split the tests into separate files by functionality if they get too big

2023-01-31 10:47 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/Helpers/SlackAlertHelperTests.cs
> +        #region GetEmojiTests
will do

2023-01-31 10:51 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/TypedClients/AppInsightsClientTests.cs
> +            deserializerMock.Verify(x => x.Deserialize(It.Is<string>(x => x == @"{ ""property"": ""value"" }")));
What's the value in asserting the result of the mock setup here? Should it be testing appInsightsClient instead, or checking that the mock was called X times?

2023-01-31 10:55 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/TypedClients/AppInsightsClientTests.cs
> +            deserializerMock.Verify(x => x.Deserialize(It.Is<string>(x => x == @"{ ""property"": ""value"" }")));
It's testing that the mocked entity has been called with the correct parameter (the JSON returned by the mocked HTTP Handler)

2023-01-31 10:58 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/TypedClients/AppInsightsClientTests.cs
> +            deserializerMock.Verify(x => x.Deserialize(It.Is<string>(x => x == @"{ ""property"": ""value"" }")));
Ok, was a bit confused as the HTTP handler mock and the deserializer mock were returning the same values

2023-01-31 11:20 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/Helpers/SlackAlertHelperTests.cs
> +        #region GetEmojiTests
done

2023-01-31 11:20 UTC, mandrici commented on src/SFA.DAS.Payments.Monitoring.Alerts.Function.UnitTests/Helpers/SlackAlertHelperTests.cs
> +        [Test]
done

2023-02-01 10:16 UTC, Stephek submitted a review, later dismissed

2023-02-03 10:01 UTC, David-B-Read approved these changes

2023-02-03 11:30 UTC, Stephek approved these changes

2023-02-03 14:54 UTC, merged