PV2-3070 - Monitor ILR resubmissions at period end
SkillsFundingAgency/das-payments-V2 pull request #1166
Opened 2023-07-21 15:56 UTC by LiamWright

2023-07-24 13:41 UTC, LiamWright commented on src/SFA.DAS.Payments.PeriodEnd.Application.UnitTests/PeriodEndJobContextMessageHandlerTests.cs
> +        private AutoMock mocker;
This actually just took me a surprising amount of time to find out why Reshaper was making this mistake upon Code Cleanup!

Turns out that the default layout for Nunit test layouts prioritises Setup/Teardown methods above variable declarations!

![image](https://github.com/SkillsFundingAgency/das-payments-V2/assets/28269309/d6692616-0ddc-430b-ba45-8cda39153308)


I'm not a fan of that sort of layout myself, but this will be something we need to agree on as a team if we are to change the default test layout

2023-07-25 10:38 UTC, abroodie requested changes
Some minor comments but I think we need to discuss the correct solution for the job status manager.

2023-07-25 10:38 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Handlers/PeriodEnd/RecordRecordPeriodEndIlrReprocessingStartedJobHandler.cs
> +            IPeriodEndJobService periodEndJobService, IPeriodEndStartJobStatusManager jobStatusManager)
This shouldn't be using the PeriodEndStartJobStatusManager as that has behaviour specific to that type of job.  We should discuss this offline for the best solution.

2023-07-27 13:34 UTC, LiamWright commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Handlers/PeriodEnd/RecordRecordPeriodEndIlrReprocessingStartedJobHandler.cs
> +                jobStatusManager.StartMonitoringJob(message.JobId, JobType.PeriodEndStartJob);
Updated

2023-07-27 13:35 UTC, LiamWright commented on src/SFA.DAS.Payments.Monitoring.Jobs.Model/JobType.cs
> +        PeriodEndIlrReprocessing
Updated

2023-07-27 13:35 UTC, LiamWright commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Handlers/PeriodEnd/RecordRecordPeriodEndIlrReprocessingStartedJobHandler.cs
> +﻿using System;
Renamed

2023-07-31 09:56 UTC, abroodie requested changes
needs a change to make sure the correct behaviour is in the correct place.

2023-07-31 09:56 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/PeriodEndJobIlrReprocessingStatusService.cs
> +    public class PeriodEndJobIlrReprocessingStatusService : JobStatusService, IPeriodEndJobIlrReprocessingStatusService
This class needs to  wait for all submission jobs to complete.  The required behaviour already exists in PeriodEndStartJobStatusService.cs.  Happy to discuss again offline.

2023-08-01 13:25 UTC, LiamWright commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/PeriodEndJobIlrReprocessingStatusService.cs
> +    public class PeriodEndJobIlrReprocessingStatusService : JobStatusService, IPeriodEndJobIlrReprocessingStatusService
I've added PerformAdditionalJobChecks override and the subsequent other methods over from PeriodEndStartJobStatusService to override JobStatusService's virtual methods.

Let me know if anything else needs doing!

2023-09-19 11:19 UTC, abroodie submitted a review, later dismissed
looka ok to me

2023-09-19 11:52 UTC, David-B-Read approved these changes

2023-10-24 13:38 UTC, David-B-Read approved these changes

2023-10-27 13:03 UTC, David-B-Read approved these changes

2023-11-08 16:07 UTC, David-B-Read submitted a review, later dismissed

2024-01-09 13:00 UTC, David-B-Read submitted a review, later dismissed

2024-03-14 14:44 UTC, David-B-Read approved these changes

2024-03-18 11:49 UTC, merged