PV2-3071 & PV2-3072 - Trigger and monitoring of period end archiving
SkillsFundingAgency/das-payments-V2 pull request #1171
Opened 2023-09-19 13:56 UTC by LiamWright

2023-09-19 14:29 UTC, David-B-Read commented on src/SFA.DAS.Payments.Audit.ArchiveService/Activities/StartPeriodEndArchiveActivity.cs
> +        var app = ConfidentialClientApplicationBuilder.Create(applicationId)
Just wondering if the URLs in here should be in config?

2023-09-19 14:35 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Handlers/PeriodEnd/RecordPeriodEndFCSHandOverCompleteJobHandler.cs
> +                logger.LogInfo($"Handling period end Fcs handover job: {message.ToJson()}");
I think FCS is an acronym so should be capitalised

2023-09-20 14:19 UTC, LiamWright commented on src/SFA.DAS.Payments.Audit.ArchiveService/Activities/StartPeriodEndArchiveActivity.cs
> +        var app = ConfidentialClientApplicationBuilder.Create(applicationId)
Have now moved these to the config

2023-09-20 14:19 UTC, LiamWright commented on src/SFA.DAS.Payments.Monitoring.Jobs.JobService/Handlers/PeriodEnd/RecordPeriodEndFCSHandOverCompleteJobHandler.cs
> +                logger.LogInfo($"Handling period end Fcs handover job: {message.ToJson()}");
Updated in the logs

2023-09-20 14:21 UTC, David-B-Read approved these changes

2023-09-26 14:27 UTC, abroodie requested changes

2023-09-26 14:27 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/GenericPeriodEndJobStatusService.cs
> +            PerformAdditionalJobChecks(JobModel job, CancellationToken cancellationToken)
This code seems to be pretty specific to the PeriodEndILRReprocessing step, not sure this is really generic behaviour that will be used for all period end jobs.

2023-10-11 09:29 UTC, abroodie submitted a review, later dismissed
Few comments but no show stoppers

2023-10-11 09:29 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/Archiving/PeriodEndArchiveStatusService.cs
> +    public class PeriodEndArchiveStatusService : JobStatusService
As this class only checks the status of the archiving job it could be simplified by removing the dependency on the base JobStatusService and simply implement IJobStatusService directly.  May be worth a new tech debt ticket to refactor this area of code.

2023-10-11 09:29 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/Archiving/PeriodEndArchiveStatusService.cs
> +    public class PeriodEndArchiverStatusSummary
Should/can this be moved to the SFA.DAS.Payments.Monitoring.Jobs.Model project?  Alternatively should it be made private to the PeriodEndArchiveStatusService class.

2023-10-11 09:29 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Jobs.Application/JobProcessing/PeriodEnd/Archiving/PeriodEndArchiveStatusService.cs
> +    public class EntityState
Should/can this be moved to the SFA.DAS.Payments.Monitoring.Jobs.Model project?  Alternatively should it be made private to the PeriodEndArchiveStatusService class.

2023-10-18 13:52 UTC, abroodie submitted a review, later dismissed

2023-10-18 15:55 UTC, David-B-Read submitted a review, later dismissed

2023-11-14 15:57 UTC, owencampbell submitted a review, later dismissed

2023-11-14 16:41 UTC, David-B-Read submitted a review, later dismissed

2023-12-15 15:46 UTC, David-B-Read approved these changes

2024-02-20 09:36 UTC, David-B-Read approved these changes

2024-03-19 15:46 UTC, owencampbell approved these changes

2024-03-19 15:59 UTC, David-B-Read approved these changes

2024-03-21 13:24 UTC, merged