Pv2 3103 metrics generation failure slack alert
SkillsFundingAgency/das-payments-V2 pull request #1173
Opened 2023-10-18 08:48 UTC by David-B-Read

2023-10-18 15:44 UTC, abroodie requested changes

2023-10-18 15:44 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application/Submission/SubmissionMetricsService.cs
> +                    throw new SubmissionMetricsTimeoutException(
Throwing a timeout exception is a bit misleading here as there could be any number of reasons why the metrics failed other than a sql timeout.  I think the ticket only talks about Metrics generation failure so probably best to stick to that domain terminology here. I would recommend throwing a SubmissionMetricsGenerationException.  Happy to discuss in the tech session though.

2023-10-18 15:44 UTC, abroodie commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application.UnitTests/Submission/SubmissionMetricsGenerationTimeoutBehaviourTests.cs
> +            _telemetry.Verify(x => x.TrackEvent(expectedMessage,
can these assertions be combined?

2023-10-19 08:59 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application/Submission/SubmissionMetricsService.cs
> +                    throw new SubmissionMetricsTimeoutException(
Renamed the exception and the custom behaviour classes to reference Generation instead of Timeout

2023-10-19 08:59 UTC, David-B-Read commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application.UnitTests/Submission/SubmissionMetricsGenerationTimeoutBehaviourTests.cs
> +            _telemetry.Verify(x => x.TrackEvent(expectedMessage,
Updated

2023-12-22 09:27 UTC, abroodie approved these changes

2024-02-23 16:05 UTC, abroodie approved these changes

2024-02-23 16:19 UTC, LiamWright approved these changes

2024-02-23 17:04 UTC, merged