PV2-3250 - Added AgeAtStartOfLearning to EarningEvents profiles
SkillsFundingAgency/das-payments-V2 pull request #1197
Opened 2024-04-15 12:55 UTC by LiamWright

2024-04-15 13:03 UTC, David-B-Read commented on src/SFA.DAS.Payments.Audit.Database/Payments2/Tables/Payments2.EarningEvent.sql
> +	AgeAtStartOfLearning TINYINT NOT NULL,
Think this should be nullable if there is no default value in the field

2024-04-15 13:03 UTC, David-B-Read commented on src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.EarningEvent.sql
> +	AgeAtStartOfLearning TINYINT NOT NULL,
Same comment as per the Audit database table

2024-04-16 14:26 UTC, LiamWright commented on src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.EarningEvent.sql
> +	AgeAtStartOfLearning TINYINT NOT NULL,
Added

2024-04-16 14:26 UTC, LiamWright commented on src/SFA.DAS.Payments.Audit.Database/Payments2/Tables/Payments2.EarningEvent.sql
> +	AgeAtStartOfLearning TINYINT NOT NULL,
Added

2024-04-16 15:04 UTC, David-B-Read submitted a review, later dismissed

2024-04-25 09:55 UTC, owencampbell submitted a review, later dismissed

2024-04-29 11:28 UTC, abroodie requested changes
Just one minor comment.

2024-04-29 11:28 UTC, abroodie commented on src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/MappingTest.cs
> +            var earningEvent = Mapper.Instance.Map<IntermediateLearningAim, ApprenticeshipContractType2EarningEvent>(learningAim);
Not sure this line is needed

2024-05-01 16:10 UTC, LiamWright commented on src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/MappingTest.cs
> +            var earningEvent = Mapper.Instance.Map<IntermediateLearningAim, ApprenticeshipContractType2EarningEvent>(learningAim);
Have removed in the latest commit

2024-05-03 11:18 UTC, abroodie submitted a review, later dismissed
looks ok to me

2024-05-08 09:08 UTC, owencampbell submitted a review, later dismissed

2024-06-18 13:50 UTC, merged