PV2-3252 - Added Co-investment recalculation and RequiredPayments mapping
SkillsFundingAgency/das-payments-V2 pull request #1199
Opened 2024-04-24 15:15 UTC by LiamWright

https://skillsfundingagency.atlassian.net/browse/PV2-3252

Steps 3.1, 3.2
https://skillsfundingagency.atlassian.net/wiki/spaces/NDL/pages/4390518797/Fully+fund+Apprenticeships+for+young+Non-Levy+Learners

2024-04-24 15:25 UTC, David-B-Read commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                    earningPeriod.period.SfaContributionPercentage = new decimal(1.0);
Does this mean 100% ESFA funded? Might be worth a comment on there to confirm

2024-04-24 15:28 UTC, David-B-Read commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                if (GetEarningType(earningPeriod.type) == EarningType.Levy)
Is this qualifier correct? I thought we were paying 100% of investment for Non Levy?

2024-04-24 15:55 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                    earningPeriod.period.SfaContributionPercentage = new decimal(1.0);
I believe this is correct

A/C:

The Co-funding rate for the ESFA contribution is recalculated to apply the 100% rate where:

Apprenticeship training start date >= 01/01/2024
Apprentice age at start of learning < 22
Levy indicator = Non-levy
Transaction type in (Learning, Completion, Balancing)


![image](https://github.com/SkillsFundingAgency/das-payments-V2/assets/28269309/04e706b5-957b-41cf-b0b1-8218c0295ccd)

2024-04-24 15:55 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                if (GetEarningType(earningPeriod.type) == EarningType.Levy)
Good catch, this needs changing then

2024-04-25 10:04 UTC, owencampbell approved these changes

2024-04-25 10:18 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                if (GetEarningType(earningPeriod.type) == EarningType.Levy)
@David-B-Read  This has been updated now

2024-04-25 10:23 UTC, David-B-Read approved these changes

2024-04-29 09:58 UTC, abroodie requested changes
Just comments regarding making the business logic for the CoInvestment override more self contained.

2024-04-29 09:58 UTC, abroodie commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/PayableEarningEventProcessor.cs
> +            var requiresRecalculation = coInvestmentCalculationService.IsEligibleForRecalculation(earningEvent);
It would probably make this code simpler if we moved the "RequiresReCalculation" decision and resulting action into the business logic within the CoInvestmentRecalculationService class, it would make this more self contained rather than splitting the business logic across the processor and service.

2024-04-29 09:58 UTC, abroodie commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/PayableEarningEventProcessor.cs
> +            if (requiresRecalculation)
same as above

2024-04-29 09:58 UTC, abroodie commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                if (earningPeriod.period.DataLockFailures is not null && earningPeriod.period.DataLockFailures.Any()) continue;
Having thought about this you probably don't need to check the apprenticeship id or datalock failures as the PayableEarningEvents should only contain valid matched periods but it does make the code safer.

2024-05-01 16:11 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/PayableEarningEventProcessor.cs
> +            var requiresRecalculation = coInvestmentCalculationService.IsEligibleForRecalculation(earningEvent);
Moved recalc logic to CoInvestmentCalculationService

2024-05-01 16:11 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Application/Processors/PayableEarningEventProcessor.cs
> +            if (requiresRecalculation)
Moved recalc logic to CoInvestmentCalculationService

2024-05-01 16:11 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Domain/Services/CoInvestmentCalculationService.cs
> +                if (earningPeriod.period.DataLockFailures is not null && earningPeriod.period.DataLockFailures.Any()) continue;
I've left this as is. You mentioned that we likely don't need to check this but it makes the code safer, so it makes sense to keep it.

2024-05-02 10:21 UTC, abroodie requested changes
code chnage to the tests covering the new logic

2024-05-02 10:21 UTC, abroodie commented on src/SFA.DAS.Payments.RequiredPayments.Domain.UnitTests/Services/CoInvestmentCalculationServiceTests.cs
> +        [TestCase(ApprenticeshipEmployerType.NonLevy, 1.0)]
It looks like the scope of this test is for NonLevy Employers, is this test case valid?  I would move this test case to a specific positive test e.g.  Should_Override_ConInvestment_Rate_For_NonLevy_Employers

2024-05-02 11:58 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Domain.UnitTests/Services/CoInvestmentCalculationServiceTests.cs
> +        [TestCase(ApprenticeshipEmployerType.NonLevy, 1.0)]
Added test as requested as well as updated test naming conventions to suit recommendation

2024-05-02 11:58 UTC, LiamWright commented on src/SFA.DAS.Payments.RequiredPayments.Domain.UnitTests/Services/CoInvestmentCalculationServiceTests.cs
> +        [TestCase(ApprenticeshipEmployerType.Levy, null)]
Updated to use 0.95

2024-05-03 11:18 UTC, abroodie approved these changes
Looks ok to me

2024-05-08 09:03 UTC, merged