Pv 2013 Period End Metric Calculation Service
SkillsFundingAgency/das-payments-V2 pull request #978
Opened 2020-07-23 08:05 UTC by keenesolutions

2020-08-24 10:06 UTC, tom-gough reviewed
Looks good, just one query I've left about a csproj change before approving.

2020-08-24 10:06 UTC, tom-gough commented on src/SFA.DAS.Payments.Monitoring.Metrics.Application/SFA.DAS.Payments.Monitoring.Metrics.Application.csproj
> +    <None Remove="Infrastructure\Configuration\**" />
Is this needed/intended as part of this ticket?

2020-08-24 10:13 UTC, tom-gough submitted a review, later dismissed

2020-08-24 10:56 UTC, tom-gough approved these changes

2020-08-25 12:13 UTC, tom-gough approved these changes

2020-09-14 15:05 UTC, hardik-desai-kcl requested changes

2020-09-14 15:05 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.Monitoring.Metrics.Data/MetricsQueryDataContext.cs
> +            var uniqueUkprns = providerMetrics.Select(x => x.Ukprn).Distinct();
I dont think this line is required, result was already grouped by Ukprn ==> group.Key.Ukprn so return amounts.Select(group => new ProviderContractTypeAmounts() would produce same result as new code

2020-09-15 06:44 UTC, carlbm commented on src/SFA.DAS.Payments.Monitoring.Metrics.Data/MetricsQueryDataContext.cs
> +            var uniqueUkprns = providerMetrics.Select(x => x.Ukprn).Distinct();
The group key is both Ukprn and Contract type, so if there are both contract types there will be two records

2020-09-15 07:53 UTC, hardik-desai-kcl submitted a review, later dismissed

2020-09-23 14:38 UTC, hardik-desai-kcl approved these changes

2020-10-23 08:46 UTC, merged