Pv2 2071 prevent period end run job executing twice
SkillsFundingAgency/das-payments-V2 pull request #989
Opened 2020-08-26 08:02 UTC by tom-gough

2020-08-26 10:29 UTC, hardik-desai-kcl requested changes

2020-08-26 10:29 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
> +                return new SqlCommand($"SELECT JobId FROM Payments2.Job WHERE DCJobId = {jobId} AND JobType = {jobType}", connection).ExecuteReader().HasRows;
could you please check that only one record is returned from DB

2020-08-26 10:30 UTC, hardik-desai-kcl requested changes

2020-08-26 10:30 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
> +                    var jobId = await jobsDataContext.GetJobId(GetJobType(taskType),
rename jobId to existingJobId?

2020-08-26 10:47 UTC, tom-gough commented on src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
> +                return new SqlCommand($"SELECT JobId FROM Payments2.Job WHERE DCJobId = {jobId} AND JobType = {jobType}", connection).ExecuteReader().HasRows;
I don't think that makes sense on this method, what would be do in the case where there is more than one job? Return false? That would be misleading.

Also there should never be a case where there is more than one job for the same DCJobId, if that is the case something fundamental has gone wrong, even before the fix in this ticket that was not happening.

2020-08-27 12:11 UTC, hardik-desai-kcl requested changes

2020-08-27 13:53 UTC, tom-gough commented on src/SFA.DAS.Payments.PeriodEnd.Application/Handlers/PeriodEndJobContextMessageHandler.cs
> +                    var jobId = await jobsDataContext.GetJobId(GetJobType(taskType),
done

2020-08-28 11:19 UTC, hardik-desai-kcl approved these changes

2020-10-28 13:55 UTC, merged